# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'voicechat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for voicechat
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  target 'voicechat-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'voicechatTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# target 'voicechat-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for voicechat-tvOS

#   target 'voicechat-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
